# Generated by Django 3.2 on 2021-07-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('user_First_name', models.CharField(max_length=50)),
                ('user_Second_name', models.CharField(max_length=50)),
                ('user_Title', models.CharField(max_length=150)),
                ('user_Birthdate', models.DateField()),
                ('user_highest_degree', models.CharField(max_length=50)),
                ('user_Experience', models.CharField(max_length=30)),
                ('Titles_you_want_to_show_in_animated_text_and_each_seprate_by_comma', models.CharField(max_length=1000)),
                ('user_Phone_No', models.CharField(max_length=10)),
                ('user_Email', models.EmailField(max_length=254, unique=True)),
                ('user_Address', models.CharField(max_length=1200)),
                ('user_Freelancer_status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Not Available', max_length=13)),
                ('user_About_Desc', models.CharField(max_length=20000)),
                ('user_image', models.ImageField(upload_to='myfolio/images')),
                ('user_cv_link', models.FileField(blank=True, upload_to='myfolio/uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=200)),
                ('email_Id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('Highest_education_name', models.CharField(max_length=300)),
                ('Highest_education_year', models.CharField(max_length=200)),
                ('Highest_education_college', models.CharField(max_length=600)),
                ('Highest_education_desc', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('Experience_name', models.CharField(max_length=300)),
                ('year_duration', models.CharField(max_length=200)),
                ('compony', models.CharField(max_length=600)),
                ('Desc_about_Experience', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('project_name', models.CharField(max_length=500)),
                ('project_catagory_name', models.CharField(max_length=150)),
                ('project_description', models.CharField(max_length=20000)),
                ('project_image', models.ImageField(upload_to='myfolio/images/projects')),
                ('project_youTubevideo_link', models.URLField(blank=True, default='#')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('user_Skill_name', models.CharField(max_length=50)),
                ('user_skill_knows_in_percententage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18)),
                ('kaggle_link', models.URLField(blank=True)),
                ('github_link', models.URLField(blank=True)),
                ('linkdin_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('facbook_link', models.URLField(blank=True)),
            ],
        ),
    ]
