# Generated by Django 3.2 on 2021-07-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_First_name', models.CharField(max_length=50)),
                ('user_Second_name', models.CharField(max_length=50)),
                ('user_Title', models.CharField(max_length=150)),
                ('user_Birthdate', models.DateField()),
                ('user_highest_degree', models.CharField(max_length=50)),
                ('user_Experience', models.CharField(max_length=30)),
                ('Titles_you_want_to_show_in_animated_text_and_each_seprate_by_comma', models.CharField(max_length=1000)),
                ('user_Phone_No', models.CharField(max_length=10)),
                ('user_Email', models.EmailField(max_length=254)),
                ('user_Address', models.CharField(max_length=1200)),
                ('user_Freelancer_status', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=13)),
                ('user_About_Desc', models.CharField(max_length=20000)),
                ('user_image', models.ImageField(upload_to='myfolio/images')),
                ('user_cv_link', models.URLField()),
            ],
        ),
    ]
