# Generated by Django 3.2 on 2021-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_Id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Highest_education_name', models.CharField(max_length=300)),
                ('Highest_education_year', models.CharField(max_length=200)),
                ('Highest_education_college', models.CharField(max_length=600)),
                ('Highest_education_desc', models.CharField(max_length=1500)),
                ('lowest_education_name', models.CharField(max_length=300)),
                ('lowest_education_year', models.CharField(max_length=200)),
                ('lowest_education_college', models.CharField(max_length=600)),
                ('lowest_education_desc', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Experience_name', models.CharField(max_length=300)),
                ('year_duration', models.CharField(max_length=200)),
                ('compony', models.CharField(max_length=600)),
                ('Desc_about_Experience', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Others_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('others_education_name', models.CharField(max_length=300)),
                ('others_education_year', models.CharField(max_length=200)),
                ('others_education_college', models.CharField(max_length=600)),
                ('others_education_desc', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=500)),
                ('project_catagory_name', models.CharField(max_length=150)),
                ('project_description', models.CharField(max_length=20000)),
                ('project_image', models.ImageField(upload_to='myfolio/images')),
                ('project_youTubevideo_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Skill_name', models.CharField(max_length=50)),
                ('user_skill_knows_in_percententage', models.IntegerField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Social_links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaggle_link', models.URLField()),
                ('github_link', models.URLField()),
                ('linkdin_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('facbook_link', models.URLField()),
            ],
        ),
    ]
