# Generated by Django 3.2 on 2021-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0002_contact_education_experience_others_education_projects_skills_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_cv_link',
            field=models.FileField(default='#', upload_to='myfolio/uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_youTubevideo_link',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='facbook_link',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='github_link',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='kaggle_link',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='linkdin_link',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='twitter_link',
            field=models.URLField(default='#', null=True),
        ),
    ]
