# Generated by Django 3.2 on 2021-07-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0002_auto_20210712_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_cv_link',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
