# Generated by Django 3.2 on 2021-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0003_alter_about_user_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_cv_link',
            field=models.URLField(blank=True),
        ),
    ]
