# Generated by Django 3.2 on 2021-07-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0003_auto_20210710_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='user_skill_knows_in_percententage',
            field=models.IntegerField(default=0),
        ),
    ]
