# Generated by Django 3.2 on 2021-07-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0004_alter_about_user_cv_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_catagory_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_youTubevideo_link',
            field=models.URLField(blank=True),
        ),
    ]
