# Generated by Django 3.2 on 2021-07-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0005_auto_20210712_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_catagory_name',
            field=models.CharField(max_length=150),
        ),
    ]
