# Generated by Django 3.2 on 2021-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0006_alter_projects_project_catagory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_links',
            name='insta_link',
            field=models.URLField(blank=True),
        ),
    ]
