# Generated by Django 3.2 on 2021-07-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0007_social_links_insta_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_Freelancer_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='social_links',
            name='user_id',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
