# Generated by Django 3.2 on 2021-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0008_auto_20210715_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=18, unique=True)),
                ('user_pass', models.CharField(max_length=20)),
            ],
        ),
    ]
