# Generated by Django 3.2 on 2021-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0002_auto_20210719_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user_Birthdate',
            field=models.CharField(max_length=50),
        ),
    ]
