# Generated by Django 3.2 on 2021-07-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('myfolio', '0005_createuserform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUserForm',
        ),
    ]
