# Generated by Django 3.2.5 on 2021-07-21 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0006_delete_createuserform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Titles_you_want_to_show_in_animated_text_and_each_seprate_by_comma_and_oneSpace',
            new_name='Titles_you_want_to_show',
        ),
    ]
