# Generated by Django 3.2 on 2021-08-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfolio', '0007_otpreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpreset',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
